### ISSUE TITLE
fourier_transform::root_of_unity(size_t n) const

### ISSUE THREAD

**Issue by m8pple** [HPCE/hpce-2015-cw3#4]
Shouldn't the twiddle factor for the FFT equal complex_t(cos(angle),-sin(angle))? I had difficulty debugging my optimal FFT as the output was being multiplied by the wrong twiddle factor, thus returning the wrong vector compared to the MATLAB version.

Do you recommend me just inverting the number at the beginning of my function or is it worth it to change the function itself and rename it to something like twiddle_factor?

**Comment by m8pple** [comment]
As far as I'm aware, both are correct, it's just a matter of preference. The
main thing we need is that n is a primitive root of unity, so:
- wn^n = 1
- forall 0 < i < n : wn^i != 1

So either of cos(2*pi/n) +- i sin(2*pi/n) should work, in the same
way that exp( +- i*pi*2 / n) would work.

Can you not adjust on the matlab side - is it not some sort of linear
transform from the clock-wise root of unity to the counter-clockwise
one?

**Comment by siddhu33** [comment]
on the matlab side, you will just have to run the ifft() command to get the forward transform instead of the fft(), as matlab works with the negative twiddle factor as described earlier. Therefore, the forward transform in the C++ code actually does the ifft instead of the fft. Of course, every test runs the transform in both directions so the original code still works as the function is bi-directional.

**Comment by m8pple** [comment]
Heh, I didn't realise it was as simple as fft <-> ifft. The fourier transform is magical...

Closing this, as I think it is ok as-is (though kudos for checking against matlab). If I
run this CW next year I'll try to remember to flip it back.
